# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

notifications:
  email:
    - gregor.decillia@statistik.gv.at
    - angelika.meraner@statistik.gv.at

# lintr setup
after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
r_github_packages:
  - cran/lintr
