# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: false
cache: packages
branches:
  only:
  - master

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libharfbuzz-dev libfribidi-dev openjdk-7-jre r-cran-rjava
  - export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/jre
  - export PATH=$PATH:$JAVA_HOME/bin
  - export LD_LIBRARY_PATH=/usr/lib/jvm/java-8-oracle/lib/amd64:/usr/lib/jvm/java-8-oracle/jre/lib/amd64/server
  - sudo R CMD javareconf

notifications:
  email:
    - gregor.decillia@statistik.gv.at
    - angelika.meraner@statistik.gv.at
    - alexander.kowarik@statistik.gv.at

# these packages don't appear in the description file since they are only
# used to check the package and build documentation. install them from github
r_packages:
  - lintr
  - pkgdown
  - covr

# avoid the following warning in devtools::check()
# "Unable to find GhostScript executable to run checks on size reduction"
apt_packages:
  - ghostscript
  - libharfbuzz-dev
  - libfribidi-dev

# lintr and coveralls
after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'covr::coveralls()'
  - Rscript -e 'lintr::lint_package()'

# build github pages via pkgdown
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
